- Patch for network_utils.py line 237   Where we see 'AttributeError: 'NoneType' object has no attribute 'GetAtoms''   caused by invalid SMILES given to recombine_edges   Xe[101Xe].Xe[102Xe].Xe[104Xe].Xe[105Xe].Xe[106Xe].Xe[107Xe].Xe[108Xe].Xe[109Xe].Xe[110Xe].[100Xe]c1c([101Xe])c([102Xe])c([103Xe])c([109Xe])c1[110Xe].[103Xe]c1c([104Xe])c([105Xe])c([106Xe])c([107Xe])c1[108Xe]